apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayoubrs/argoCD.git
    targetRevision: HEAD
    path: p3/synced_repo/playground/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true