apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: part-three
  namespace: inception
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  service name hereeeeeeeeeeeeeeeeeeeeeee=========********
            port:
              number: 1337