apiVersion: v1
kind: Service
metadata:
  namespace: inception
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 8080
# targetPort should be the same as containerPort

---

apiVersion: v1
kind: Service
metadata:
  namespace: inception
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: inception
  name: app3-service
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 8080