apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 8080
# targetPort should be the same as containerPort
