# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ing-service
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name:  app3-service
#             port:
#               number: 1337 

###
# this header dosent work
###
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#   name: cluster-ingress
#   namespace: default

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes
  namespace: inception
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  app3-service
            port:
              number: 1337
  - host: app1.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app1-service
            port:
              number: 1337
  - host: app2.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app2-service
            port:
              number: 1337