apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-argocd
  namespace: argocd
spec:
  project: default
  source:
     repoURL: https://github.com/ayoubrs/kubernetes/tree/main/p3/cluster_synced_repo
    targetRevision: HEAD
    path: p3/synced_repo/playground/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true