Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"




  config.vm.define "amyaS" do |control|
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "amyaS"]

      vb.memory = 512
      vb.cpus = 1
      vb.name = "amya"
    end
    config.vm.network "private_network", ip: "192.168.42.110"
    config.vm.hostname = "amyaS"
  end

  config.vm.define "amyaSW" do |control|
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "amyaSW"]
      vb.memory = 512
      vb.cpus = 1
      vb.name = "amyas"
    end
    config.vm.network "private_network", ip: "192.168.42.111"
    config.vm.hostname = "amyaSW"
  end

  # config.vm.network "forwarded_port", guest: 80, host: 8080
end

