apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: part3
  # namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: playground-service
            port:
              number: 1337